# Generated by Django 4.2 on 2024-01-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Available Quantity'),
        ),
        migrations.AddField(
            model_name='storinginformation',
            name='action',
            field=models.CharField(choices=[('+', 'Add'), ('-', 'Remove')], default='+', max_length=10, verbose_name='Action'),
            preserve_default=False,
        ),
    ]
